### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by shakeelmohamed** [shakeelmohamed/toothpicz#3]
# Website
## UI Flow:
- [ ] Facebook Auth
- [ ] Check for barcode scanner app
- [ ] Main menu/dashboard
  -  View history of previous sessions
  -  Scan, start/stop session
## Web (photographer interface):
- [ ] Implement filepicker
# Mobile Apps
## Android:
- [ ] XZing
- [ ] Setup UI flow
- [ ] POST/GET
- [ ] Connectivity with Azure DB
- [ ] SQLite local DB
- [ ] Sync algorithm
## iOS:
- [ ] Facebook SDK, login via sample session login example
- [ ] Base UI
- [ ] Timer functionality (unix timestamp)
- [ ] Get an iOS device for testing
- [ ] XZing
- [ ] Setup UI flow
- [ ] POST/GET
- [ ] Connectivity with Azure DB
- [ ] SQLite local DB
- [ ] Sync algorithm
